import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/header'
import { Footer } from '@/components/footer'
import { WalletActionsProvider } from '@/contexts/wallet-actions-context'

const roboto = Roboto({
  variable: '--font-roboto-sans',
  weight: ['400', '500', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'dApp JoKenPo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt">
      <body
        className={`${roboto.variable} bg-gray-900 font-sans text-white antialiased`}
      >
        <WalletActionsProvider>
          <div className="mx-auto max-w-screen-lg">
            <Header />
            <div className="flex h-[calc(100vh-80px)] flex-col items-center">
              {children}
              <Footer />
            </div>
          </div>
        </WalletActionsProvider>
      </body>
    </html>
  )
}
